[package]
name = "pinocchio-memo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
pinocchio = "0.8.4"

[dev-dependencies]
mollusk-svm = "0.1.5"
solana-sdk = "2.2.1"